path: ../data  # Root directory for datasets, relative to this YAML file's location
train: calibration_images_eye/images # Path to training images, relative to 'path'
val: calibration_images_eye/images   # Path to validation images, relative to 'path'
nc: 2
names: ['open_eye', 'close_eye'] 